export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const ADD_PRODUCTS = "ADD_PRODUCTS";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const EDIT_PRODUCT = "EDIT_PRODUCT";
